spring:
  application:
    name: wf
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:subscription-app-client}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:kjiht2UNn43x6DiJY2KNvKLhGj5camdY}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
              - roles
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
            user-name-attribute: wf-user
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

app:
  security:
    public-paths:
      - "/"
      - "/api/hello"
      - "/swagger-ui/**"
      - "/swagger-ui.html"
      - "/v3/api-docs/**"
    role-prefix: "ROLE_"
    claim-name: "realm_access"
    roles-claim-name: "roles"
    role-mappings:
      "/api/secure/admin": "ROLE_ADMIN"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.sumittuladhar.wf: DEBUG
